"""SQLModel entities: Protocol and ProtocolAction.

A Protocol is a weekly plan of 3–7 daily actions auto-generated by the Coach
from the patient's goals, biomarkers, survey, and recent signals. Each action
carries a category (movement / sleep / nutrition / mind / supplement), a target,
a rationale linking back to Coach, and streak tracking.

One-to-many relationship:
  Protocol (1) → ProtocolAction (N) via ProtocolAction.protocol_id FK

ProtocolAction rows are the self-tracking unit that feeds the streak engine and
the VitalityOutlook projection.
"""

from __future__ import annotations

import datetime

from sqlalchemy import Index
from sqlmodel import Field, SQLModel


def _utcnow() -> datetime.datetime:
    """Return current UTC time as timezone-naive datetime (CLAUDE.md pattern)."""
    return datetime.datetime.now(datetime.UTC).replace(tzinfo=None)


class Protocol(SQLModel, table=True):
    """A weekly longevity protocol for a patient.

    Generated by the protocol_generator service via LLM; contains 3–7 actions
    (stored as ProtocolAction rows referencing this row's id).

    ``status`` lifecycle: "active" → "completed" | "superseded".
    """

    __tablename__ = "protocol"

    # Named index on patient_id — do NOT add index=True to Field below.
    __table_args__ = (Index("ix_protocol_patient_id", "patient_id"),)

    id: int | None = Field(default=None, primary_key=True)

    # patient_id indexed via __table_args__ above
    patient_id: str = Field(foreign_key="patient.patient_id")

    # Monday of the protocol week (date, not datetime — no TZ concerns)
    week_start: datetime.date

    # Lifecycle: "active" | "completed" | "superseded"
    status: str

    # Name of the LLM model used to generate (optional, for audit)
    generated_by: str | None = Field(default=None)

    # Timestamp of generation (naive UTC)
    created_at: datetime.datetime = Field(default_factory=_utcnow)


class ProtocolAction(SQLModel, table=True):
    """A single daily action within a Protocol.

    Carries streak tracking (streak_days, completed_today) so the outlook
    engine can compute momentum from action-level data.

    Queried via: SELECT * FROM protocol_action WHERE protocol_id = :pid
    """

    __tablename__ = "protocol_action"

    __table_args__ = (Index("ix_protocol_action_protocol_id", "protocol_id"),)

    id: int | None = Field(default=None, primary_key=True)

    # FK to the parent Protocol row
    protocol_id: int = Field(foreign_key="protocol.id")

    # One of: movement | sleep | nutrition | mind | supplement
    category: str

    # Short human-readable label (e.g. "Walk 25 minutes")
    title: str

    # One-line wellness-framed rationale linking back to Coach
    rationale: str = Field(default="")

    # Human-readable target (e.g. "25 min", "22:30 bedtime")
    target_value: str | None = Field(default=None)

    # Streak tracking — per action
    streak_days: int = Field(default=0)
    completed_today: bool = Field(default=False)
