"""SQLModel entity: VitalityOutlook.

Stores the computed near-term vitality projection for a patient at a specific
time horizon (3, 6, or 12 months). Multiple rows per patient are allowed — one
per (patient_id, horizon_months, computed_at) combination. Callers typically
read the latest row per horizon.

Outlook formula (from docs/05-data-model.md):
  Outlook(h months) = Score_now + Σ (streak_weight[category] × streak_days × decay(h))

Product invariant: breaking a streak flattens the outlook curve but never
drops the current Vitality Score. This is enforced at the service layer, not
here.

Recomputed on login and on every protocol-action completion event.
"""

from __future__ import annotations

import datetime

from sqlalchemy import Index
from sqlmodel import Field, SQLModel


def _utcnow() -> datetime.datetime:
    """Return current UTC time as timezone-naive datetime (CLAUDE.md pattern)."""
    return datetime.datetime.now(datetime.UTC).replace(tzinfo=None)


class VitalityOutlook(SQLModel, table=True):
    """Computed vitality projection for a patient at a given time horizon.

    ``horizon_months`` must be one of: 3, 6, 12.
    ``projected_score`` is bounded 0–100 (enforced at the service layer).
    ``narrative`` is a one-sentence wellness-framed summary generated by the
    outlook narrator service (LLM-generated).
    """

    __tablename__ = "vitality_outlook"

    # Named index on patient_id — do NOT add index=True to Field below.
    __table_args__ = (Index("ix_vitality_outlook_patient_id", "patient_id"),)

    id: int | None = Field(default=None, primary_key=True)

    # Patient isolation boundary — indexed via __table_args__
    patient_id: str = Field(foreign_key="patient.patient_id")

    # Time horizon for this projection: 3, 6, or 12 (months)
    horizon_months: int

    # Projected composite score (0–100)
    projected_score: float

    # One-sentence wellness narrative from the narrator LLM call
    narrative: str

    # When this outlook was computed (naive UTC)
    computed_at: datetime.datetime
