"""Integration test: Rebecca (PT0199) positive-trajectory showcase — T7.

Ingests the real ``data/`` directory against a live Postgres instance (via
testcontainers) and asserts that Rebecca's end-to-end story renders correctly:

  1. Exactly 90 wearable rows are loaded.
  2. The most recent wearable date is 2026-04-10 (last day of the 90-day arc).
  3. At least 60 daily_log rows exist (T5 generated 90).
  4. At least 10 meal_log rows exist (T5 generated 14).
  5. At least one meal_log row has a non-empty ``longevity_swap``.
  6. Every meal_log row has a ``photo_uri`` starting with ``manual://``.
  7. ``compute_vitality`` produces a composite score in the 70–85 band.
  8. The trend sparkline has at least 14 points (TREND_WINDOW_DAYS=30 → 30 pts).
  9. ``compute_outlook`` projections are monotonically non-decreasing across the
     3- / 6- / 12-month horizons, and each horizon is ≥ the current score.
 10. No projected score exceeds the CEILING of 95.0.

The test uses the real ``data/`` directory (``repo_root/data``); path resolution
is verified relative to this file's location:
``Path(__file__).resolve().parents[3] / "data"``
  → ``<repo>/backend/tests/integration/`` = __file__ parent
  → [0] = integration/
  → [1] = tests/
  → [2] = backend/
  → [3] = repo root
  → / "data" = repo_root/data

Run with::

    uv run pytest backend/tests/integration/test_rebecca_showcase.py -x
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import pytest
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

import app.adapters.csv_source  # noqa: F401 — registers @register("csv")
from app.models import EHRRecord, LifestyleProfile, Patient, WearableDay
from app.models.daily_log import DailyLog
from app.models.meal_log import MealLog
from app.repositories import (
    DailyLogRepository,
    EHRRepository,
    MealLogRepository,
    PatientRepository,
    WearableRepository,
)
from app.services.outlook_engine import CEILING, compute_outlook
from app.services.unified_profile import UnifiedProfileService
from app.services.vitality_engine import compute_vitality

# ---------------------------------------------------------------------------
# Path to the canonical seed data directory
# ---------------------------------------------------------------------------

#: Resolves to ``<repo_root>/data`` regardless of where pytest is invoked from.
#: Path chain: this_file → integration/ → tests/ → backend/ → repo_root → data/
_DATA_DIR: Path = Path(__file__).resolve().parents[3] / "data"


# ---------------------------------------------------------------------------
# Helper: fetch LifestyleProfile for a patient via raw SQL
# ---------------------------------------------------------------------------


async def _get_lifestyle(session: AsyncSession, patient_id: str) -> LifestyleProfile | None:
    """Fetch the LifestyleProfile for ``patient_id``.

    There is no dedicated LifestyleProfileRepository — the model uses
    ``patient_id`` as its own PK, so we fetch it directly with a
    ``select`` statement following the project's ``getattr`` pattern for
    mypy-safe column comparisons.

    Args:
        session:    The active async session.
        patient_id: The patient to look up.

    Returns:
        The ``LifestyleProfile`` row, or ``None`` if not found.
    """
    pid_attr = getattr(LifestyleProfile, "patient_id")
    stmt = select(LifestyleProfile).where(pid_attr == patient_id)
    result = await session.execute(stmt)
    return result.scalars().first()


# ---------------------------------------------------------------------------
# Showcase test
# ---------------------------------------------------------------------------


@pytest.mark.integration
async def test_rebecca_showcase_end_to_end(db_session: AsyncSession) -> None:
    """Verify PT0199's positive-trajectory story renders correctly end-to-end.

    This test ingests the real ``data/`` directory — the canonical seed data
    generated by T5 — and then asserts the full pipeline from raw CSVs through
    vitality engine and outlook projections.

    The test is designed to surface data-drift immediately: if Rebecca's
    generated data changes (e.g. seed script tweaked, CSV manually edited),
    the score-band assertion provides a precise failure message.
    """
    # ------------------------------------------------------------------
    # Precondition: data dir must exist and contain the required CSVs.
    # ------------------------------------------------------------------
    assert _DATA_DIR.is_dir(), (
        f"Seed data directory not found: {_DATA_DIR!r}. "
        "Run scripts/generate_rebecca_data.py to regenerate."
    )

    # ------------------------------------------------------------------
    # 1. Ingest: run the CSV adapter against the real data/ directory.
    # ------------------------------------------------------------------
    svc = UnifiedProfileService(session=db_session, llm_provider=None)
    report = await svc.ingest("csv", data_dir=_DATA_DIR)

    assert report.patients_ingested > 0, (
        f"Ingest reported 0 patients — check {_DATA_DIR!r}"
    )

    # ------------------------------------------------------------------
    # 2. Fetch Rebecca's patient row (required by compute_vitality).
    # ------------------------------------------------------------------
    patient_repo = PatientRepository(db_session)
    patient = await patient_repo.get(patient_id="PT0199")
    assert patient is not None, "PT0199 not found in Patient table after ingest"

    # ------------------------------------------------------------------
    # 3. Fetch wearable telemetry — use a large window to capture all 90 days.
    # ------------------------------------------------------------------
    wearable_repo = WearableRepository(db_session)
    wearable = await wearable_repo.list_recent(patient_id="PT0199", days=120)

    assert len(wearable) == 90, (
        f"Expected exactly 90 wearable rows for PT0199, got {len(wearable)}. "
        "Check data/wearable_telemetry_1.csv for PT0199 rows."
    )

    most_recent_date = max(w.date for w in wearable)
    assert most_recent_date == date(2026, 4, 10), (
        f"Most recent wearable date should be 2026-04-10, got {most_recent_date}. "
        "Check data/wearable_telemetry_1.csv — T5 should end on 2026-04-10."
    )

    # ------------------------------------------------------------------
    # 4. Fetch EHR records.
    # ------------------------------------------------------------------
    ehr_repo = EHRRepository(db_session)
    ehr = await ehr_repo.list(patient_id="PT0199")

    assert len(ehr) > 0, "PT0199 has no EHR records after ingest"

    # ------------------------------------------------------------------
    # 5. Fetch lifestyle profile.
    # ------------------------------------------------------------------
    lifestyle = await _get_lifestyle(db_session, "PT0199")
    # Lifestyle may be None if the survey CSV is missing, but T5 updates it.
    # We assert it exists so scoring is not based on defaults alone.
    assert lifestyle is not None, (
        "PT0199 has no LifestyleProfile after ingest. "
        "Check data/lifestyle_survey.csv — PT0199 row should be updated by T5."
    )

    # ------------------------------------------------------------------
    # 6. Fetch daily logs.
    # ------------------------------------------------------------------
    daily_log_repo = DailyLogRepository(db_session)
    daily_logs = await daily_log_repo.list_for_patient("PT0199")

    assert len(daily_logs) >= 60, (
        f"Expected at least 60 daily_log rows for PT0199, got {len(daily_logs)}. "
        "T5 should generate 90 rows in data/daily_log.csv."
    )

    # ------------------------------------------------------------------
    # 7. Fetch meal logs.
    # ------------------------------------------------------------------
    meal_log_repo = MealLogRepository(db_session)
    meal_logs = await meal_log_repo.list_recent(patient_id="PT0199", limit=20)

    assert len(meal_logs) >= 10, (
        f"Expected at least 10 meal_log rows for PT0199, got {len(meal_logs)}. "
        "T5 should generate 14 rows in data/meal_log.csv."
    )

    has_longevity_swap = any(
        m.longevity_swap and m.longevity_swap.strip() for m in meal_logs
    )
    assert has_longevity_swap, (
        "No meal_log row has a non-empty longevity_swap. "
        "T5 must include longevity_swap suggestions in data/meal_log.csv."
    )

    for meal in meal_logs:
        assert meal.photo_uri is not None and meal.photo_uri.startswith("manual://"), (
            f"meal_log row (analyzed_at={meal.analyzed_at}) has photo_uri={meal.photo_uri!r}; "
            "all meal_log rows ingested from CSV must use the 'manual://' sentinel prefix."
        )

    # ------------------------------------------------------------------
    # 8. Compute vitality score.
    # ------------------------------------------------------------------
    result = compute_vitality(patient, ehr, wearable, lifestyle)

    assert 70.0 <= result.score <= 85.0, (
        f"Rebecca composite score {result.score:.2f} is outside the expected 70–85 band. "
        "If the formula or seed data changed, verify docs/10-vitality-formula.md "
        "and update this band accordingly."
    )

    assert len(result.trend) >= 14, (
        f"Expected at least 14 trend points (TREND_WINDOW_DAYS=30), "
        f"got {len(result.trend)}. "
        "Rebecca has 90 wearable days — the trend window should be fully populated."
    )

    # ------------------------------------------------------------------
    # 9. Compute outlook projections.
    # ------------------------------------------------------------------
    projections = compute_outlook(
        "PT0199",
        result.score,
        streak_days=14,
        protocol_adherence=0.85,
    )

    assert set(projections.keys()) == {3, 6, 12}, (
        f"compute_outlook must return exactly keys {{3, 6, 12}}, got {set(projections.keys())}"
    )

    # Each horizon must be at least as high as the current score.
    for horizon, projected in projections.items():
        assert projected >= result.score, (
            f"Outlook horizon {horizon}m ({projected:.2f}) is below the current score "
            f"({result.score:.2f}). The projection must never drop below current."
        )

    # Monotonically non-decreasing: 3m ≤ 6m ≤ 12m.
    assert projections[3] <= projections[6], (
        f"Outlook is not monotonic: 3m={projections[3]:.2f} > 6m={projections[6]:.2f}. "
        "Longer horizons must capture at least as much of the reachable gap."
    )
    assert projections[6] <= projections[12], (
        f"Outlook is not monotonic: 6m={projections[6]:.2f} > 12m={projections[12]:.2f}. "
        "Longer horizons must capture at least as much of the reachable gap."
    )

    # ------------------------------------------------------------------
    # 10. No projection may exceed the ceiling.
    # ------------------------------------------------------------------
    for horizon, projected in projections.items():
        assert projected <= CEILING, (
            f"Outlook horizon {horizon}m ({projected:.2f}) exceeds the CEILING ({CEILING}). "
            "The model must always clamp to [current_score, CEILING]."
        )
