"""Smart notification request/response DTOs.

``SmartNotificationRequest`` is the inbound payload for triggering an
LLM-generated push notification.

``SmartNotificationResponse`` extends ``AIResponseEnvelope`` so it always
carries the wellness disclaimer and AI observability metadata.

The notification body is generated by the LLM using ``notifications.system.md``
and is never delivered via a real push channel in the MVP — it is returned
to the client to display in-app.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.ai_common import AIResponseEnvelope


class SmartNotificationRequest(BaseModel):
    """Inbound payload for ``POST /v1/patients/{pid}/notifications/smart``.

    ``trigger_kind`` identifies the event that prompted the notification
    (e.g. ``streak_at_risk``, ``protocol_due``, ``weekly_check_in``).
    ``context`` carries the event-specific data the LLM uses to personalise
    the notification copy.
    """

    model_config = ConfigDict(from_attributes=True)

    trigger_kind: str = Field(
        ...,
        description=(
            "Notification trigger identifier, e.g. "
            "'streak_at_risk' | 'protocol_due' | 'weekly_check_in'"
        ),
    )
    context: dict[str, Any] = Field(
        default_factory=dict,
        description="Event-specific context data passed to the LLM for personalisation",
    )


class SmartNotificationResponse(AIResponseEnvelope):
    """Response from the Smart Notification endpoint.

    Inherits ``disclaimer`` and ``ai_meta`` from ``AIResponseEnvelope``.
    ``title``, ``body``, and ``cta`` are the three notification copy fields
    generated by the LLM and surfaced to the client.
    """

    title: str = Field(..., description="Short notification title (≤60 chars recommended)")
    body: str = Field(
        ...,
        description="Notification body text with personalised wellness framing",
    )
    cta: str = Field(
        ...,
        description="Call-to-action label, e.g. 'Log activity' or 'View protocol'",
    )
